#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "Checking commit message..."
message="$(cat $1)"

# Check if the string has at least 9 characters
if [ ${#message} -lt 9 ]; then
  echo "🚨 Wrong commit message! 😕"
  echo "Error: Commit message should have at least 9 characters."
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  exit 1
fi

# Check if the string contains 2 words
wordCount=$(echo "$message" | wc -w)
if [ $wordCount -lt 2 ]; then
  echo "🚨 Wrong commit message! 😕"
  echo "Error: Commit message should contain at least 2 words."
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  exit 1
fi

echo "✅ Commit message is valid!"

echo "✅ commit-msg hook finished successfully"