#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# check if code is formatted
if ! npm run format:check
then
  echo "🚨 Code is not formatted! 😕"
  echo "Please run 'npm run format' and commit again."
  exit 1
fi

# check for eslint errors
npm run lint

# check comments
npm run comment:check


# run tests
npm run test

# check if app is buildable
npm run build

echo "✅ pre-commit hook finished successfully"